# Generated by Django 5.1 on 2024-08-12 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='pdf_document',
            field=models.FileField(default=1, upload_to='documents', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
            preserve_default=False,
        ),
    ]
